### ISSUE TITLE
seek_position update

### ISSUE THREAD

**Issue by audiophonics** [pavoni/pyroon#1]
Hello,

When calling roonapi.zone_by_name, the "seek_position" value is updated only if we change "volume" or "state"
The callback return : "zones_seek_changed:  [u'160160ebd918de93c888a51a481101e89859']"

But I have no idea how to get the new seek value when callback is detected ?

Thanks for your tips.

**Comment by marcelveldt** [comment]
Hi, sorry for the reply. The seek value should be part of the zone object itself.
So roonapi.zones["zone_id"] will hold all actual zone values
