### ISSUE TITLE
Comparing items should be case insensitive

### ISSUE THREAD

**Issue by inonio** [pavoni/pyroon#26]
I think we should be able to specify strings without having case sensitivity.
e.g - both examples should work, but currently only the first one does:
`Library/Artists/Neil Young/Harvest`
`Library/Artists/neil young/harvest`

**Comment by pavoni** [comment]
It seems there can be issues (given these could be in multiple languages)

https://stackoverflow.com/questions/319426/how-do-i-do-a-case-insensitive-string-comparison

Is this causing you a problem?

**Comment by pavoni** [comment]
Seems like this may get close https://stackoverflow.com/questions/319426/how-do-i-do-a-case-insensitive-string-comparison/40551443#40551443

**Comment by pavoni** [comment]
Not sure this is an issue, so closing unless there is more feedback.
