### ISSUE TITLE
"host" variable doesn't appear to be doing anything

### ISSUE THREAD

**Issue by shersch** [pavoni/pyroon#34]
first of all, thank you so much for working on this library; I am so excited to start using it.  Anyway, when I use the example code just to print out the zones, it seems to completely disregard the "host" variable.  My local machine is 192.168.1.7, where I am running Roon, but my Roon Server is 192.168.1.27, and my bridge is 1.10.  With the host set to 1.27, it still goes straight to the local machine, and if I close Roon on the local machine, it will try to use 1.10.  When I close both 7 and 10, it does find 27 and everything seems to work from there.

**Comment by pavoni** [comment]
Can you post the code example you're using?

This is probably the one to look at:-

https://github.com/pavoni/pyroon/blob/master/examples/play.py

If you specify `server` this should do as you expect. 

```roonapi = RoonApi(appinfo, token, server)```

The discovery example shows how to use discovery - which is more complex that might be idea! The discovery in the base library usually does what you describe (choses the first reply - which is usually the client on the local machine - which is no use at all!).

**Comment by shersch** [comment]
ah!  my apologies; I didn't look at the examples, I was just going from what the readme showed!  I added the host variable to RoonApi() and it's working perfectly.  Thanks, and keep up the great work!

**Comment by pavoni** [comment]
I'll fix the read me - thanks for the heads up.
