### ISSUE TITLE
Can you please provide Pypi SDIST format or a Release on Github?

### ISSUE THREAD

**Issue by onkelbeh** [pavoni/pyroon#4]
Hi,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository), hope you don't mind.

Therefor I would need a release file either at Pypi in SDIST format, or as a tar.gz on github.
Home Assistant currently requires: roonapi-0.0.21

A release on Github would be easy and OK, but a Pypi tar.gz release would be preferred, because this could take use of Gentoo's mirror system. Most of the other integrations do both.

Thanks
\B.

**Comment by pavoni** [comment]
Should now be done. I'll submit a PR to bump HA to 0.0.22
