### ISSUE TITLE
Support for Volume Control Endpoint

### ISSUE THREAD

**Issue by SebuZet** [pavoni/pyroon#46]
Hi,

I've updated roonapi from very old version and i've noticed that support for volume control endpoints was removed.
Is it possible to bring it back?
I'm using this functionality in my plugin for controlling volume on soekris Dam1021 DAC.
With current version of pyroon it is not achievable.

Thanks in advance for your reply.
BR,
Seba

**Comment by pavoni** [comment]
Hi Seba,

When I took over the library I couldn't understand how that code worked - or find a way to use it.

I didn't want to have something in the library that I wasn't able to support - so I removed it.

I'd welcome a PR to add it back - as long as you can also provide an example of how it's used to the example directory.

**Comment by pavoni** [comment]
I should perhaps add that my focus has been on tidying up and improving the integration with Home Assistant - hence removing things that weren't needed for that.

And should you need the old code - you can get the library before I modified it here: https://github.com/pavoni/pyroon/tree/64103fec69289ef1de16fdc489a18235e75ef2f9

**Comment by Joegratz** [comment]
FWIW, I have patched these features back in on my local fork, it works fine, when I have time I will do a PR with an example. (Fine to leave this closed.)
