### ISSUE TITLE
Playing tags isn't working

### ISSUE THREAD

**Issue by Ramblurr** [pavoni/pyroon#59]
**Problem**: You cannot play tags with `roon.play_media(zone_id, ["Library", "Tags", "mytag"])` It also doesn't work in HA when using the media browser.

**Error**:
```
  File "/var/home/ramblurr/src/mycroft/mycroft-core/.venv/lib/python3.10/site-packages/roonapi/roonapi.py", line 579, in play_media
    if take_action["hint"] != "action":
KeyError: 'hint'
```

Looking at the JSON output from the roon api, you can see that the action hint is not there:

```json
{
    "items": [
      {
        "title": "Brass",
        "subtitle": "1 Item",
        "image_key": null,
        "item_key": "730:0",
        "hint": "list"
      }
    ],
    "offset": 0,
    "list": {
      "level": 1,
      "title": "Tags",
      "subtitle": "1 Result",
      "image_key": null,
      "count": 1,
      "display_offset": null
    }
  }
```
Yet from the Roon app one can search for a tag and then shuffle it, so there's got to be some way to play tags.. any ideas?

**Comment by Ramblurr** [comment]
Submitted a PR to fix the crash, but one still can't play tags.

When browsing one level deeper into the tag itself, the json is:

```json
{
    "items": [
      {
        "title": "Play Tag",
        "subtitle": null,
        "image_key": null,
        "item_key": "785:0",
        "hint": "action_list"
      },
      {
        "title": "Gallowstreet Brass Band",
        "subtitle": "Artist, 3 Albums",
        "image_key": "00aab2e33650023564000d856df09be7",
        "item_key": "785:1",
        "hint": "list"
      }
    ],
    "offset": 0,
    "list": {
      "level": 1,
      "title": "Brass",
      "subtitle": "1 Item",
      "image_key": null,
      "count": 2,
      "display_offset": null
    }
  }
```

You can see the "Play Tag" `action_list`.. browsing into that:

```json
{
    "items": [
      {
        "title": "Shuffle",
        "subtitle": null,
        "image_key": null,
        "item_key": "821:0"
      },
      {
        "title": "Start Radio",
        "subtitle": null,
        "image_key": null,
        "item_key": "821:1"
      }
    ],
    "offset": 0,
    "list": {
      "level": 3,
      "title": "Play Tag",
      "subtitle": null,
      "image_key": null,
      "count": 2,
      "display_offset": null,
      "hint": "action_list"
    }
  }
```

The shuffle and start radio actions do not have `hint`s! Is this a bug in the roon api?

**Comment by Ramblurr** [comment]
For comparison, here is the action level of an Artist:

```json
{
    "items": [
      {
        "title": "Shuffle",
        "subtitle": null,
        "image_key": null,
        "item_key": "835:0",
        "hint": "action"
      },
      {
        "title": "Start Radio",
        "subtitle": null,
        "image_key": null,
        "item_key": "835:1",
        "hint": "action"
      }
    ],
    "offset": 0,
    "list": {
      "level": 3,
      "title": "Play Artist",
      "subtitle": null,
      "image_key": null,
      "count": 2,
      "display_offset": null,
      "hint": "action_list"
    }
  }
```

**Comment by pavoni** [comment]
Thanks for the investigation.

My guess is that it is a bug in the api as you suggest, but hard to be sure.

I spent quite a bit of time experimenting to get the radio stuff working, which isn’t very consistent with the artist / album browsing.

If you’ll willing to experiment - perhaps  start by changing the code to ‘default’ the hint if it’s missing and see how the code copes.

**Comment by Ramblurr** [comment]
Yea, I tried by commenting out the final check for the hint..and the tag "station" played as expected. That's why I think it's a Room bug..the hint should be there.

One could check if the title of the supposed action key has one of the action keywords in it, like "Play" or "Shuffle" but I'm not sure if those strings are localized or not depending on your Room Core language

**Comment by pavoni** [comment]
BTW the code path for playing via the browser might be different, although harder to test that since you need to integrate into HA.

**Comment by Ramblurr** [comment]
Sounds like a plan.

I'm building a Roon skill for Mycroft (an open source privacy first voice assistant) using your library
https://github.com/Ramblurr/mycroft-roon-skill

It's working really well.. it's just a huge PITA to search for media but this isn't your fault, it's that the room browse API is designed for GUIs not programmatic search.

**Comment by pavoni** [comment]
Wow - cool project!

I can imagine playing media is hard.

The best I could do is fake up some paths 

https://www.home-assistant.io/integrations/roon/

**Comment by Ramblurr** [comment]
Yea, in my first version of the roon skill I was using your "paths" and it worked, but it was quite slow from the users perspective due to all the API calls behind the scenes. So today I rewrote it to just use the browsing api, walking/traversing the different levels.

BTW I use the paths feature in Home Assistant..we have lovelace dashboard buttons for our favorite Roon playlists.
