### ISSUE TITLE
Websocket and websocket-client are missing in Arch Linux

### ISSUE THREAD

**Issue by smangels** [pavoni/pyroon#9]
Hi,
many thanks for this app in Python but when installing it into a virtual environment botch _websocket_ and _websocket-client_ are missing as dependencies in the packet description.

BR,
Sebastian Mangelsen

**Comment by smangels** [comment]
Appreciated! many thanks for the effort.

**Comment by pavoni** [comment]
Thanks for reporting it - would have caused other issues and I hadn’t realised!

Give it a few more days - will do another release with a few more issues fixed.
